management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,httptrace,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: Customer Service
    version: 1.0.0
    description: Manages Customers and Addresses

springdoc:
  api-docs:
    path: /api/customer/v3/api-docs
  swagger-ui:
    path: /api/customer/swagger-ui.html
