package com.tnf.common_dto.dto.account;

import java.math.BigDecimal;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// Cross-service view of a bank account. No account business rules (minimum-balance,
// overdraft, interest accrual) live here — those belong to account-service's model layer.
// accountType is a String (not an enum) on purpose: the AccountType enum lives in
// account-service's model package. The type-specific fields are nullable and only populated
// for the matching accountType.
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BankAccountDto {

    // Null/absent on a create request, populated on responses.
    private String id;

    // Bank-assigned identifier, generated by account-service.
    private String accountNumber;

    // Reference to the owning customer (customer-service owns the Customer itself).
    @NotBlank(message = "customerId is required")
    private String customerId;

    // "SAVINGS" or "CURRENT" — validated against account-service's AccountType enum.
    @NotBlank(message = "accountType is required")
    @Pattern(regexp = "SAVINGS|CURRENT", message = "accountType must be SAVINGS or CURRENT")
    private String accountType;

    // Current balance. May be negative for a CURRENT account within its overdraft limit.
    private BigDecimal balance;

    // SAVINGS only: balance must stay at or above this after a withdrawal.
    @PositiveOrZero(message = "minimumBalance cannot be negative")
    private BigDecimal minimumBalance;

    // SAVINGS only: annual interest rate as a fraction (e.g. 0.035 = 3.5%).
    @PositiveOrZero(message = "interestRate cannot be negative")
    private BigDecimal interestRate;

    // CURRENT only: maximum permitted overdraft.
    @PositiveOrZero(message = "overdraftLimit cannot be negative")
    private BigDecimal overdraftLimit;
}
