spring.application.name=config-server

server.port=8888
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=file:///Users/ahana.srinathmurthy/Library/CloudStorage/OneDrive-Informaplc/Documents/Microservices/Config files
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# for git
#spring.cloud.config.server.git.uri=https://github.com/AhanaS07/Microservices-Config-Files.git